import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// import localFont from "next/font/local";

// Roboto font will load only on this page.
const roboto = Roboto({ subsets: ["latin"], weight: "900", variable: "--my-font" });

// To load local font files.
// const roboto = localFont({src: [
//   {
//     path: "./fonts/Roboto-Medium.ttf", weight: "500"
//   }
// ],})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
      {/* <body className={roboto.variable}>{children}</body> */}
    </html>
  );
}
